# Generated by Django 3.1 on 2020-11-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_info', models.CharField(max_length=250)),
                ('du_lead', models.CharField(max_length=250)),
                ('manager', models.CharField(max_length=250)),
                ('ams', models.CharField(max_length=250)),
                ('leads', models.CharField(max_length=250)),
            ],
        ),
    ]
