# Generated by Django 3.1 on 2020-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ams', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Du_lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du_lead', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='ams',
        ),
        migrations.RemoveField(
            model_name='info',
            name='du_lead',
        ),
        migrations.RemoveField(
            model_name='info',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='info',
            name='manager',
        ),
    ]
