# Generated by Django 3.1 on 2020-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bofa', '0002_auto_20201110_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_Organisation', models.CharField(max_length=500)),
                ('certificate_Name', models.CharField(max_length=500)),
                ('date_of_Completion', models.DateField()),
                ('expiration_Date', models.DateField()),
            ],
        ),
    ]
